title: "Mathematical Notes"
summary: "「Quantum Fields and Strings: A Course for Mathematicians」を読みながら書いているノート"
topics: ["数学", "物理"]
published: true
price: 0
chapters:
  - math1
  - math2
  - math3
  - math4
  - math5
  - math6
  - math7
  - math8
