graph LR
  FT[場の理論] -->|停留点| EM[運動方程式]
  FT -->|解空間上のシンプレクティック構造| QFT[場の量子論]
  QFT --> QM[量子力学]

  style FT fill:#ffe4e6,stroke:#fecdd3,stroke-width:2px
  style QFT fill:#e0e7ff,stroke:#c7d2fe,stroke-width:2px
  style EM fill:#f1f5f9,stroke:#e2e8f0,stroke-width:1px
  style QM fill:#f1f5f9,stroke:#e2e8f0,stroke-width:1px
